mash-up-kr/VitaminC_Web

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

close: #1 
- 템플릿 내용 수정 환영 !
- CODEOWNERS 내 핸들 맞는지 봐주세요 !

feat: set CODEOWNERS file and template for issue, pr

---

.gitignore
src/__tests__/utils/date.test.ts
src/app/page.tsx
src/components/common/button.tsx
src/utils/date.ts

feat: getDiffDate 텍스트

---

.gitignore
next.config.mjs
package-lock.json
package.json
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts
src/app/api/error-alert/route.ts
src/app/global-error.tsx
src/instrumentation.ts

Feature/sentry 에러 처리 작업했어요

---

src/app/search/page.tsx
src/app/search/recent-keywords.tsx
src/app/search/search-form.tsx
src/components/search-input.tsx
src/hooks/use-is-server.ts
src/utils/storage/index.ts

feat: search page

---

src/components/BottomModal.tsx
src/components/common/Modal/Modal.tsx
src/components/common/Modal/Portal.tsx
src/hooks/use-click-outside.ts
src/hooks/use-event-listener.ts
src/hooks/use-modal-transition.ts
src/hooks/use-render-state.ts

#26
- 애니메이션은 framer를 사용하려다가 스터디에서 제가 만든 애니메이션 훅 써봤습니다~ 그걸로 인한 훅이 좀 있어요!

feat: bottom modal with animation

---

src/app/actions.ts
src/app/setting/page.tsx

feat: setting page

---

src/app/globals.css
src/app/intro/page.tsx
src/app/map/[mapId]/page.tsx
src/app/search/[query]/result-search-box.tsx
src/app/search/[query]/result-search-list.tsx
src/app/search/suggest-place-list.tsx
src/app/setting/page.tsx
src/components/common/input.tsx
src/components/intro/steps/invite.tsx
src/components/intro/steps/login.tsx
src/components/intro/steps/new-map.tsx
src/components/korrk-kakao-map.tsx
src/components/place/place-auto-search-item.tsx
src/components/place/place-map-popup.tsx
src/components/tag-list.tsx

feat: style, korrk kakao map

---

src/app/setting/page.tsx
src/components/boarding-pass/boarding-info-pass.tsx

feat: go to next map when withdrawl map

---

src/app/map/[mapId]/page.tsx
src/app/map/[mapId]/place-list-bottom-sheet.tsx
src/app/place/[placeId]/place-box.tsx
src/app/search/[query]/result-search-box.tsx
src/app/search/[query]/result-search-list.tsx
src/components/place/place-list-item.tsx
src/components/place/place-map-popup.tsx
src/components/tag-list.tsx
src/constants/place.ts
src/types/api/place.ts
src/types/map/kakao-raw-type.ts
src/utils/api/index.ts
src/utils/score.ts

chore: set rate at Map and fix filter, and... jobboo..

---

src/app/map/[mapId]/page.tsx
src/app/map/[mapId]/place-list-bottom-sheet.tsx
src/app/place/[placeId]/page.tsx
src/app/place/[placeId]/place-box.tsx
src/app/place/[placeId]/place-delete-modal.tsx
src/app/place/[placeId]/register/page.tsx
src/app/place/[placeId]/register/register-box.tsx
src/app/search/[query]/result-search-box.tsx
src/app/search/[query]/result-search-list.tsx
src/app/search/empty-result-box.tsx
src/app/search/search-box.tsx
src/app/search/search-form.tsx
src/app/search/suggest-place-list.tsx
src/components/korrk-kakao-map.tsx
src/components/place/kakao-rating.tsx
src/components/place/menu-list.tsx
src/components/place/place-auto-search-item.tsx
src/components/place/place-map-popup.tsx
src/hooks/use-user.ts
src/types/api/place.ts
src/utils/api/index.ts
src/utils/format.ts

feat: search, place, register api

---

src/app/api/token/route.ts
src/app/setting/page.tsx

섹쉬하게 쿠키 지우기
- 전달 사항 1
- 전달 사항 2

fix: logout

---

src/hooks/use-kakao-share.ts

feat: set mobile url at kakao share

---

src/app/map/[mapId]/page.tsx
src/app/map/[mapId]/search-anchor-box.tsx
src/app/place/[placeId]/place-box.tsx
src/app/place/[placeId]/place-top-information.tsx
src/app/search/[query]/result-place-map-popup.tsx
src/app/search/[query]/result-place-popup-skeleton.tsx
src/app/search/[query]/result-search-box.tsx
src/components/kakao-map/marker.tsx
src/components/korrk-kakao-map.tsx
src/components/place/menu-list.tsx
src/components/place/place-list-item.tsx
src/components/place/place-map-popup.tsx
src/components/tag-list.tsx
src/types/api/place.ts
src/utils/format.ts
src/utils/number.ts

feat: qa in result

---

src/app/map/[mapId]/map-info-modal.tsx
src/app/map/[mapId]/page.tsx
src/hooks/use-fetch.ts
src/utils/date.ts

캐싱 관련 이슈를 해결했어요
- 캐싱은 정말 신경써야 하는 게 많군요... 🫠

fix: fix caching related bugs

---

src/app/map/[mapId]/page.tsx
src/app/map/[mapId]/place-list-bottom-sheet.tsx
src/app/not-found.tsx
src/app/place/[placeId]/register/page.tsx
src/components/loading-indicator.tsx

fix: fix bugs found during self-QA

---

src/app/api/token/route.ts
src/services/user.ts

쿠키를 삭제하지 않으니까 로그아웃이 되지 않는군요! 그래서 쿠키를 다른 방법으로 삭제해보았어요 ^^*
- 최최최종... 

fix: implement cookie deletion by cookies().set

---

src/app/intro/page.tsx
src/app/invite/page.tsx
src/app/map/[mapId]/map-info-modal.tsx
src/app/place/[placeId]/page.tsx
src/app/place/[placeId]/register/page.tsx
src/components/boarding-pass/boarding-info-pass.tsx
src/components/boarding-pass/invited-boarding-pass.tsx
src/components/boarding-pass/types.ts
src/components/intro/steps/invite.tsx
src/services/invitation.ts
src/services/user.ts

- 사실 fix는 두 줄이고 나머지는 다 리팩토링입니다 😇 고치는 김에 보기 싫었던 코드 분리해내다가 그만 이렇게 되었어요 ㅎㅎ..

fix: allow existing users to board by invitation

---

src/components/common/bottom-sheet/index.tsx
src/hooks/use-user-geo-location.ts

feat: improve ux

---

src/app/map/[mapId]/map-info-modal.tsx
src/app/map/[mapId]/place-list-bottom-sheet.tsx
src/app/place/[placeId]/place-box.tsx
src/app/place/[placeId]/place-delete-modal.tsx
src/app/search/[query]/result-place-map-popup.tsx
src/app/search/[query]/result-search-list.tsx
src/components/boarding-pass/boarding-info-pass.tsx
src/components/place/place-map-popup.tsx

fix: bug bug bug

---

src/app/intro/page.tsx

fix: add missing deps array

---

.prettierrc.json
package-lock.json
src/app/intro/page.tsx
src/components/intro/steps/invite.tsx
src/hooks/use-safe-router.ts
src/services/invitation.ts

fix: everything

---

src/app/intro/page.tsx
src/components/intro/steps/invite.tsx
src/services/invitation.ts

chore: remove log

---

package-lock.json
src/components/common/proxy-image.tsx

fix: show skeleton when fetch image

---

src/app/globals.css
src/app/map/[mapId]/place-list-bottom-sheet.tsx
src/components/common/bottom-sheet/index.tsx
src/components/kakao-map/kakao-map.tsx

fix: bottom sheet!!!

---

src/components/common/custom-toast.tsx

feat: update the design of custom-toast

---

src/app/test-design/page.tsx
src/components/intro/steps/login/intro-carousel.tsx
src/components/like-button.tsx
src/hooks/use-user-geo-location.ts

- 지금 서버 이슈로 쿠키를 받을 수 없어서 test-design 페이지에 좋아요 버튼 올려두었습니당

feat: update like button design

---

src/app/setting/page.tsx

Feat: 임시 이벤트로 코드좀 건드렸어요

---

src/app/map/[mapId]/page.tsx
src/app/map/[mapId]/place-list-bottom-sheet.tsx
src/app/place/[placeId]/place-box.tsx
src/app/search/[query]/result-place-map-popup.tsx
src/app/search/[query]/result-search-list.tsx
src/components/place/place-map-popup.tsx
src/constants/place.ts
src/models/api/place.ts
src/utils/format.ts

chore: update likedUserIds to likedUsers

---

src/app/map/[mapId]/page.tsx
src/app/map/[mapId]/place-list-bottom-sheet.tsx
src/app/search/[query]/result-search-list.tsx
src/components/place/place-map-popup.tsx
src/constants/place.ts
src/models/api/place.ts
src/utils/api/index.ts
src/utils/format.ts

chore: rename some likedUsers to likedUser

---

src/app/globals.css
src/app/place/[placeId]/place-box.tsx
src/app/recommendation/page.tsx
src/app/search/[query]/result-search-list.tsx
src/app/search/suggest-place-list.tsx
src/app/test-design/page.tsx
src/components/kakao-map/gps-button.tsx
src/components/kakao-map/kakao-map.tsx
src/components/place/place-action-buttons.tsx
src/hooks/use-user-geo-location.ts
src/models/map.ts

feat: auth in place detail

---

package-lock.json
src/app/map/[mapId]/place-list-bottom-sheet.tsx
src/app/place/[placeId]/place-box.tsx

fix: update likedUser of sliced placeList

---

src/app/recommendation/ai-recommendation.ts
src/app/recommendation/chat-item.tsx
src/app/recommendation/guide.ts
src/app/recommendation/page.tsx

feat: improve ai recommendation page

---

src/app/recommendation/guide.ts
src/components/kakao-map/gpt-intro-modal.tsx

feat: update copy of ai recommendation

---

src/app/recommendation/ai-recommend-lottie.tsx
src/app/recommendation/page.tsx

fix: divide component to avoid unnecessary rendering

---

src/app/my-map/[mapId]/page.tsx

Style: 맵 관리 > 하단 잘리는 현상 수정

---

src/app/recommendation/page.tsx

fix: fix recommend page height css

---

README.md
src/app/intro/page.tsx
src/app/recommendation/page.tsx
src/hooks/use-infinite-scroll.ts

- README 업데이트하려고 보다가 ai 추천 화면이 깨지는 것을 발견하는 바람에 코드를 정말정말 조금만 수정하게 되었어요. 이 PR 반영되고 나면 README 잠수함 업데이트할 예정!

fix: fix some bugs
